env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
